### ISSUE TITLE
Add supporting metadata to benchmarks

### ISSUE THREAD

**Issue by Fdawgs** [anonrig/fast-querystring#18]
Would be beneficial for the benchmark table to have supporting information such as:

- Specs of the machine running the benchmarks
- Node version
- Run date and time

Similar to https://github.com/fastify/benchmarks#benchmarks

This would allow viewers to know how current/accurate the benchmarks are.

**Comment by anonrig** [comment]
That's right. I'm currently running them on my machine. Here's the information, but eventually I want to run them on Github workflows (if it produces consistent benchmarks)

- Machine: Apple M1 Max, 64GB Mem
- Node: 18.8.0
