### ISSUE TITLE
Run benchmark on every pull request

### ISSUE THREAD

**Issue by anonrig** [anonrig/fast-querystring#32]
We should definitely add a command to run benchmarks on every pull request and add a comment for the result

**Comment by Uzlopak** [comment]
Sry, saw this now. 

Benchmarks make imho no sense to be part of the CI/CD pipeline. The github workflow runner have to share resources with other instances and you have 0 control over the CPU and RAM of the machine. If github upgrades their machines partially then you get sometimes faster and sometimes slower results.

**Comment by anonrig** [comment]
I agree. Closing the issue.
