### ISSUE TITLE
Adding Benchmark and Test For Browser and Maybe Edge Runtime

### ISSUE THREAD

**Issue by baraeb92** [anonrig/fast-querystring#41]
Hi, 

I understand that the goal of this library is to replace legacy node:querystring and is intended to be used in the Node environment.

But the benchmark also runs against other libraries that run on the browser. 

So, based on the discussion I have with my team (notes that I'm a Product Manager, not a web developer), when the team is using a platform like NextJS, for example, they wanted to know whether the library will work in either Node and Edge environment (SSR), or on the browser (CSR). 

So I have a few suggestions related to this: 

1. You can make it clear in the documentation that it is not recommended or untested for this library to be used in the browser or non-Node environment

2. You can also add a test to use this on Edge and Browser environment

3. And related to performance to not only show benchmark related to how fast the library is doing specific operations (i.e., stringifying) but also how it will impact other metrics such as CPU and memory load (which will affect infra cost) and also Time to First Byte and Page Load (when running on the browser). This will show a complete picture of the tradeoff and when to use or not use this library. 

I like what you guys are doing, and I hope this feedback will improve the library. 

Sincerely,

**Comment by anonrig** [comment]
I added tests for edge runtime and browsers, but your other suggestions might not be feasible on a project of this size. Hopefully the test coverage (100%) on multiple environments would help with your concerns.
